language: python

# using container based testing is faster, but you can't use sudo
sudo: false

python:
    # - "2.7_with_system_site_packages"
    # - "3.6"
    - "2.7"

# command to install dependencies that require sudo
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            # - python-zmq
            # - python-nose
            # - python-numpy
            # - python-six
            # - python-yaml
            - libzmq3-dev
            - sox
            - python-opencv
            - libopencv-dev
            - libportaudio-dev
            - python-numpy
            # - python-scipy
            - gnustep

# install other libraries using pip
install:
    - pip install -U pip setuptools
    # - pip install -U pyzmq pyyaml opencvutils simplejson wit quaternions numdifftools pyrk
    - pip install -U pyzmq pyyaml opencvutils simplejson quaternions pyrk
    - pip install .
    # - pip install -U -r requirements.txt

# command to run tests
script: nosetests -v -w tests test.py
